### ISSUE TITLE
x, y, and z broken when ra and dec are None

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/healpix-alchemy#16] opened 2021-08-23 17:52 UTC
Sometimes, ra and dec are set to None in Skyportal. Since x, y, and z are computed automatically in the latest release, these functions will fail, i.e.

>   **dfl(lambda ra, dec: cos(rad(ra)) * cos(rad(dec))))
E   TypeError: must be real number, not NoneType

Could we modify the functions to be like:

cos(rad(ra)) * cos(rad(dec) if ra is not None else None

Or similar? Or what do you think @lpsinger ?

**Comment by lpsinger** [comment] 2021-08-23 19:02
The `ra` and `dec` columns are not nullable. How would you get this error message?

**Comment by mcoughlin** [comment] 2021-08-23 19:04
@stefanv do you have intuition for what is going on here? I don't understand how this works in SP or maybe I am off base.

**Comment by mcoughlin** [comment] 2021-08-23 20:27
@lpsinger https://github.com/skyportal/healpix-alchemy/blob/main/healpix_alchemy/point.py#L27 Are they actually nullable? Or maybe you just mean they should be?

**Comment by lpsinger** [comment] 2021-08-23 20:28
I didn't intend them to be nullable, but they might be.

**Comment by mcoughlin** [comment] 2021-08-23 20:30
@lpsinger Do you have a strong opinion here? It looks like folks have been using the fact that it is Nullable in their dev work.

**Comment by mcoughlin** [comment] 2021-08-23 20:47
Oops, looks like we are just rehashing the discussion in #13 .

**Comment by lpsinger** [comment] 2021-08-23 20:49
Duplicate of #13.

**Closed by lpsinger** 2021-08-23 20:49 UTC
